services:
  #Zookeeper Cluster
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    ports:
    - "2181:2181"

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - "2182:2181"

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - "2183:2181"
  # End of Zookeeper

  kafka1:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 
 
      KAFKA_LISTENER_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093   # <-- Added this line
    ports:
      - "9093:9093"

  kafka2:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_INTERFACE: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENER_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093  
    ports:
      - "9094:9093"

  kafka3:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_INTERFACE: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENER_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9093  
    ports:
      - "9095:9093"

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka














  log-producer:
    build:
      context: ./log-producer
    container_name: log-producer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka:9092

  log-consumer:
    build:
      context: ./log-consumer
    container_name: log-consumer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka:9092

  event-producer:
    build:
      context: ./event-producer
    container_name: event-producer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka:9092

  event-consumer:
    build:
      context: ./event-consumer
    container_name: event-consumer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka:9092

  
  event-consumergroup1:
    build:
      context: ./event-consumer-group
    container_name: event-consumergroup1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka:9092
      CONSUMER_ID: 1

  event-consumergroup2:
    build:
      context: ./event-consumer-group
    container_name: event-consumergroup2
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka:9092
      CONSUMER_ID: 2

